AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120
